def exception_error():
    raise Exception('tests')
