def exception_error():
    raise Exception('test')
